// PLACEHOLDER — Generated by FlutterFire CLI (`flutterfire configure`)
// After setting up your Firebase project:
//   1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   2. Run: flutterfire configure
// This will auto-generate the real file with your project credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Actual Firebase project credentials ───
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUoGlfgXEYy-7SZUaEGSN0yuD9S7wPfrM',
    appId: '1:1062036834408:web:3c705a6e839551425c13dd',
    messagingSenderId: '1062036834408',
    projectId: 'lovesnaps-app-2026',
    authDomain: 'lovesnaps-app-2026.firebaseapp.com',
    storageBucket: 'lovesnaps-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWky4Ba7OBql7qqah2XNN_118FwQx1oBM',
    appId: '1:1062036834408:android:477c617019e5d11b5c13dd',
    messagingSenderId: '1062036834408',
    projectId: 'lovesnaps-app-2026',
    storageBucket: 'lovesnaps-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOPNPxGubup6-_Amq3nj7ooKBKDFr8HnM',
    appId: '1:1062036834408:ios:183d9c0c3146acce5c13dd',
    messagingSenderId: '1062036834408',
    projectId: 'lovesnaps-app-2026',
    storageBucket: 'lovesnaps-app-2026.firebasestorage.app',
    iosBundleId: 'com.lovesnaps.app',
  );
}
